option('testing', type: 'boolean', value: false, description: 'Build unit tests')
option('examples', type: 'boolean', value: false, description: 'Build examples')
option('nanospline', type: 'boolean', value: false, description: 'Enable nanospline extension')
option('python', type: 'boolean', value: false, description: 'Build python binding')
